### ISSUE TITLE
SmoothBoot (Forge) causes data generation to crash on startup

### ISSUE THREAD

**Issue by Jonathing** [UltimateBoomer/smoothboot-fabric#11]
Hi! I've been using SmoothBoot as a dependency in my Forge workspaces since it helps with boot times and makes modding generally a whole lot easier. However, there's an issue with SmoothBoot and data generation clashing at startup

## The Problem

The `UtilMixin` class in SmoothBoot modifies the bootstrap which the data gen needs at the very start of its process in order to start data fixing entries for data generation. Here's a link to a secret gist I've uploaded containing the stacktrace and the full log. https://gist.github.com/Jonathing/6d0a52dac76ca3da6c45a8226e43f98b

## A Workaround

I've submitted a PR (#12) that proposes a workaround to this problem. Keep in mind that it just disables everything when datagen is found to be running. If you have a better solution than I do, feel free to use that instead.

---

All in all, I've had a very good experience with SmoothBoot and this has been the only problem I've come across, so I thought I'd bring it up here. Cheers and have a good one.

**Comment by UltimateBoomer** [comment]
I think I found the problem. The config for smooth boot wasn't initialized when running data generation, which is causing the null pointer exception. I'll release a new version that fixes this bug.

**Comment by Jonathing** [comment]
oh sick. you could probably initialize it in the datagen mixin I made because it's injected right before bootstrap is run. hope that goes well for ya!

**Comment by UltimateBoomer** [comment]
It should be fixed now. I've uploaded a new version (1.2.1) to jcenter which contains this fix. Thanks for finding this bug!

**Comment by Jonathing** [comment]
eyy no problem mate. Have a good one!
