### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by ceoz-0** [UltimateBoomer/smoothboot-fabric#13]
So, im trying to make a modpack for anarchy players, with the best optimization mods i can found.
But, since it's for anarchy players, it include hacked clients, in this case inertia... For some reason, inertia simply dont work with smoothboot... Minecraft boots properly, but inertia doesn't start with it.
You have some ideia from what's happening ?

**Comment by UltimateBoomer** [comment]
Hmm, that's weird. What minecraft version is the modpack for? Unfortunately inertia isn't open source, so I don't really know what mixins it uses.

**Comment by ceoz-0** [comment]
Sorry, its for 1.16.4
