### ISSUE TITLE
Causes "Incompatible Mod List" tag on multiplayer servers.

### ISSUE THREAD

**Issue by ZandercraftGames** [UltimateBoomer/smoothboot-fabric#15]
This issue does not break the ability to connect to servers but still marks itself as a mod required server-side for a server to be compatible with the mod. This is just a visual annoyance but is probably a pretty quick and easy fix. Not to mention the fact that it will result in less confusion by users of the mod. A client mod shouldn't mark itself as causing server incompatibilities.

This causes the red X to appear on servers displaying "Incompatible FML modded server. Server mod list is not compatible."

Log:
```
[B#617]  [21:14:34.549] [Netty Client IO #3/INFO] [client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [smoothboot]
```

**Comment by UltimateBoomer** [comment]
It should be fixed now, I'm going to roll out an update for all forge versions that includes this fix.

**Comment by ZandercraftGames** [comment]
@UltimateBoomer Thanks bro.
