### ISSUE TITLE
Clarification needed for "Main worker tread count"

### ISSUE THREAD

**Issue by NebelNidas** [UltimateBoomer/smoothboot-fabric#16]
In the wiki, it says this:
![image](https://user-images.githubusercontent.com/48808497/111062350-9985ff80-84a8-11eb-90f7-6496bf67640f.png)

What do you mean by
> and may have an impact on in-game performance.

?

Does it limit the threads the game can use while it's running? That would be quite undesirable and limit performance, wouldn't it?

**Comment by UltimateBoomer** [comment]
The main worker executor is used by resource loading, and setting a lower thread count will make loading slower but it does not make the game run slower. What I mean by it affecting in-game performance is that some loading tasks might be ran while the in game, or some mods might use this executor to run stuff. So setting it to a lower number might create more stutters while playing, but it generally shouldn't affect performance that much.
