### ISSUE TITLE
1.18-1.7.0 dependency compiled with errors on maven

### ISSUE THREAD

**Issue by REALMWTH** [UltimateBoomer/smoothboot-fabric#25]
Check logs here:
https://jitpack.io/com/github/ultimateboomer/mc-smoothboot/1.18-1.7.0/build.log

I am unable to compile my project because of that.

**Comment by fantahund** [comment]
You are using a wrong Java version to build. According to the log you are using Java 8 but in this case you need Java 16. For the current version even Java 17.
