### ISSUE TITLE
1.12.2 forge

### ISSUE THREAD

**Issue by bigenergy** [UltimateBoomer/smoothboot-fabric#3]
Could you add support for 1.12.2? Thx.

**Comment by UltimateBoomer** [comment]
I'll make an attempt, though keep in mind that this mod mainly uses Mixin to inject code, so getting it to work in 1.12 won't be easy.

**Comment by KubiRemPL** [comment]
It would be sooooo cooool to load 1.12.2 faster than ever.
Thanks for attempt.
Good Luck!!!

**Comment by UltimateBoomer** [comment]
Update: 1.12 doesn't benefit from the improvements of this mod because it doesn't use executors, so a 1.12 version probably won't do much.
