### ISSUE TITLE
Mod Menu not showing Configuration

### ISSUE THREAD

**Issue by Obscure2020** [UltimateBoomer/smoothboot-fabric#33]
I was just reading the SmoothBoot wiki, and I realized it says that you should be able to configure its options in Mod Menu. I had never noticed that before, so I booted up my game to see if I could.

That's when I noticed the bug: the configuration button in Mod Menu does nothing with SmoothBoot. Literally nothing. The button becomes colored when you select SmoothBoot, suggesting that a configuration menu _should_ be available, but clicking on that button does nothing.

Just to make sure this wasn't the fault of any other mods, I created a new instance in my launcher with only SmoothBoot, Mod Menu, and Fabric API. Sure enough, the bug was still there.

Here's the specific version information of the instance I created to test the bug:
- Minecraft 1.18.2
- Fabric 0.13.3
- Fabric API 0.48.0+1.18.2
- Mod Menu v3.1.0 for 1.18.2
- smoothboot-fabric-1.18.2-1.7.0

**Comment by UltimateBoomer** [comment]
The way Smooth Boot implements the config button is that it will open the mod's json config file with an external editor. Do you have an associated program for the .json format?

**Comment by Obscure2020** [comment]
For whatever reason, I didn't. Just told my system to use VSCode to open all `.json` files and now the button does work.

I now also have a few questions:
1. Why don't you have an actual Mod Menu configuration menu?
1. The SmoothBoot wiki says that the main thread count is calculated based on the total number of threads available. When is this calculation done? Is it performed every time the game boots or just when SmoothBoot is first installed?

**Comment by UltimateBoomer** [comment]
Thank you for your questions.

1. A while back the Smooth Boot did actually have a config menu, which was implemented using Cloth Config. However, it was an overkill solution when the mod is so simple in what it does (basically just changing a few parameters in thread creation). Besides, all config options required a restart to apply, and most the time the mod is just set and forget. So, with versions after 1.17, the mod menu UI was removed.
2. The calculation was done on first run when the config file is created, so if you change the config later, running the game will not override the values.

**Comment by Obscure2020** [comment]
Thanks for answering my questions. Your answer to question 2 was informative... Looks like I'll have to open a new issue.

**Comment by Obscure2020** [comment]
https://github.com/UltimateBoomer/mc-smoothboot/issues/34
