### ISSUE TITLE
Config Issue, Very Weird

### ISSUE THREAD

**Issue by MonotoneDevelopment** [UltimateBoomer/smoothboot-fabric#37]
I try to open the config, but instead it opens Adobe After Affects. Very strange... lmao

Running this on fabric, macOS latest

**Comment by ghost** [comment]
looks like a "your system" issue

**Comment by MonotoneDevelopment** [comment]
There isn't any way that it's a system issue, because there isn't any call for that in system logs n'shit

**Comment by ghost** [comment]
> There isn't any way that it's a system issue, because there isn't any call for that in system logs n'shit

That is an issue with the configuration of your file associations. SmoothBoot should use the standard system APIs for opening stuff. Check file associations for unknown files, Adobe is known to mess stuff up.

**Comment by MonotoneDevelopment** [comment]
Going to close issue, Adobe has a weird issue where it will take precedence over any other app as the default opening application if it supports it. This is kind of the case with many other applications, and I don't know if macOS just does that, but it's annoying, and I hope they fix it.
