### ISSUE TITLE
Can i make a forge port of smooth boot mod for Minecraft 1.18.2 and Up ?

### ISSUE THREAD

**Issue by AbdElAziz333** [UltimateBoomer/smoothboot-fabric#43]
Hello, i am abdelaziz, a lot of forge modpacks needs your smooth boot mod, and i don't think you are going to support the forge mod loader, so can i update it for minecraft 1.18.2 and up ?
And don't worry i will not drop the support of it and i accept every condition you ask for.
Also i accept if you ask for not to make it official.
Despite the MIT license.

**Comment by UltimateBoomer** [comment]
Yes, if you want to work on and release an updated version of this mod for forge, go ahead!

**Comment by AbdElAziz333** [comment]
Thank You!
