### ISSUE TITLE
Wrong default main thread count

### ISSUE THREAD

**Issue by Rad586** [UltimateBoomer/smoothboot-fabric#49]
Mod version: 1.7.0
Game version: 1.18.2 fabric
CPU: i7 10870H
The default main thread count is 1/2 of cpu threads, but it automatically sets 15, which is not 1/2 of my cpu thread( actually it's 8). 

edit: stupid questions: I noticed a tiny difference when changing the main thread count from 15 to 8, it feels "lighter" when standing still and shaking the camera. Would lower main thread count improving frame rate somehow? In heavily modded minecraft ( with a lot of structures and biomes added), would a lower thread count causing less lag spikes ( slower chunk generating)?

**Comment by vadcx** [comment]
Duplicate of #34 

> edit: stupid questions: I noticed a tiny difference when changing the main thread count from 15 to 8, it feels "lighter" when standing still and shaking the camera.

I guess this feeling is how you perceive a lower input lag (presentation latency). It's possible that you do get better input lag with fewer threads.

**Comment by Rad586** [comment]
> 
Thanks for replying! Closing this since it's a duplicate.
