### ISSUE TITLE
Add a warning when many Thread Count

### ISSUE THREAD

**Issue by Miros77** [UltimateBoomer/smoothboot-fabric#5]
The processor is overheating

And the Blue Screen appeared

[Blue Screen.zip](https://github.com/UltimateBoomer/mc-smoothboot/files/5563436/Blue.Screen.zip)

**Comment by UltimateBoomer** [comment]
Try setting main worker thread count to a lower value (mainThreadCount in config file
). It will make the game use less threads and reduce heat output.

**Comment by Miros77** [comment]
Add a warning! when you put 10!

**Comment by UltimateBoomer** [comment]
Would it be ok if I add a warning line in the configuration?

**Comment by Miros77** [comment]
this so that other people do not overheat the processor!!!

**Comment by Miros77** [comment]
> Would it be ok if I add a warning line in the configuration?

Yes!

**Comment by UltimateBoomer** [comment]
I've added a notice in the configuration.
