### ISSUE TITLE
Allow >=1.19.4

### ISSUE THREAD

**Issue by someone5678** [UltimateBoomer/smoothboot-fabric#52]
Currently, "Smooth Boot" hardcoded supported version to 1.19.4.
But as I tested, changing `"minecraft": "1.19.4",` to `"minecraft": ">=1.19.4",` in fabric.mod.json makes this mod works with 1.20.

The only problem is config menu is broken.
It launches config json file instead of modmenu's menu screen.

**Comment by someone5678** [comment]
@UltimateBoomer

**Comment by ghost** [comment]
@UltimateBoomer Can confirm, works on 1.20.

**Comment by Kennybust** [comment]
@UltimateBoomer @fantahund 
This mod is still a saver and a must have for really low end devices,

Look.

With
![With](https://github.com/UltimateBoomer/mc-smoothboot/assets/80032036/e07118fb-5301-479c-a2a8-5897b69a9b9a)
Without
![without](https://github.com/UltimateBoomer/mc-smoothboot/assets/80032036/e3fa9c3a-e6a7-4773-a57f-f6e229d6b522)
it needs to be continued, please.
With smooth boot my pc can do 120 fps unlocked, without it's just a stuttery mess that can't maintain stable 60 fps just standing. 1.19.4 and later didn't fix anything

**Comment by ghost** [comment]
Smooth Boot provides threading management options that no other mod does, and I'd love to see it maintained and expanded.

**Comment by Kennybust** [comment]
Agreed, it needs to be rebranded and developed, improved further @fantahund

**Comment by fantahund** [comment]
The mod is no longer needed in 1.20, Mojang has fixed the problem in 1.19.4

**Comment by Kennybust** [comment]
No they didn't... Did you see my report? Look up @fantahund

**Comment by ghost** [comment]
> The mod is no longer needed in 1.20, Mojang has fixed the problem in 1.19.4

There still isn't any other thread priority management mod like this one. Smooth Boot needs a rebranding and an expansion, not abandonment.
