### ISSUE TITLE
CurseForge question

### ISSUE THREAD

**Issue by Finoway** [UltimateBoomer/smoothboot-fabric#6]
Hi, I'm asking myself a question. I saw that there are other branches of the mod in forge for example are not on curseforge do you think to put them ? (because if I wasn't going on the github I didn't see it) 

Cordially Finoway,

**Comment by UltimateBoomer** [comment]
Hello Finoway,
The forge versions are uploaded in a [separate project](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-forge). It has versions from 1.14 to 1.16.

**Comment by Finoway** [comment]
sorry for the inconvenience I had not seen I'm blind but then maybe specify fabric on the other? and remove the forge version?

**Comment by UltimateBoomer** [comment]
Yeah the way the curseforge page is set up does makes it somewhat confusing. I've just updated the mod page so it's clear that it is the fabric version.

**Comment by Finoway** [comment]
Thank you, it's better that way ^^
