### ISSUE TITLE
Cloth Config v4.8.2 doesn't work with 1.16.1

### ISSUE THREAD

**Issue by NeeEoo** [UltimateBoomer/smoothboot-fabric#9]
Crash Report: https://pastebin.com/6NxVmnhf

**Comment by UltimateBoomer** [comment]
Unfortunately newer cloth config versions no longer works with 1.16.1, so there isn't much I can do. The mod should still work fine and you can still edit the config file manually.

**Comment by NeeEoo** [comment]
You could provide multiple versions such as one for 1.16.1 and one for the other versions.

**Comment by UltimateBoomer** [comment]
Ok I'll include a 1.16.1 version for the next release.

**Comment by UltimateBoomer** [comment]
I've released the 1.16.1 version which should no longer crash on opening the config.
